kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  PodSecurity: true
nodes:
- role: control-plane
  #image: kindest/node:v1.23.10 # v1.24.4 25.0
- role: worker
  #image: kindest/node:v1.22.13
