---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mb
  region: eu-west-1
  tags:
    managed_by: 'eksctl'
    karpenter.sh/discovery: mb
    #kubernetes.io/cluster/mb: true
  version: '1.26'

#vpc:
#    clusterEndpoints:
#        publicAccess: true
#        privateAccess: true

iam:
  withOIDC: true
#  serviceAccounts:
#  - metadata:
#      name: karpenter
#      namespace: karpenter
#    attachPolicy:
#      Version: "2012-10-17"
#      Statement:
#      - Effect: Allow
#        Resource: "*"
#        Action:
#        # Write Operations
#        - "ec2:CreateLaunchTemplate"
#        - "ec2:CreateFleet"
#        - "ec2:RunInstances"
#        - "ec2:CreateTags"
#        - "ec2:TerminateInstances"
#        - "ec2:DeleteLaunchTemplate"
#        # Read Operations
#        - "ec2:DescribeLaunchTemplates"
#        - "ec2:DescribeInstances"
#        - "ec2:DescribeSecurityGroups"
#        - "ec2:DescribeSubnets"
#        - "ec2:DescribeImages"
#        - "ec2:DescribeInstanceTypes"
#        - "ec2:DescribeInstanceTypeOfferings"
#        - "ec2:DescribeAvailabilityZones"
#        - "ec2:DescribeSpotPriceHistory"
#        - "ssm:GetParameter"
#        - "pricing:GetProducts"
#        # for !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/KarpenterNodeRole-${ClusterName}"
#        - "iam:PassRole"

#cloudWatch:
#  clusterLogging:
#    enableTypes: ["audit", "authenticator"]
#    logRetentionInDays: 7

#karpenter:
#  version: 'v0.25.0' # Exact version must be specified
#  createServiceAccount: true # default is false
#  defaultInstanceProfile: 'KarpenterNodeInstanceProfile-mb' # default is to use the IAM instance profile created by eksctl

fargateProfiles:
  - name: karpenter
    selectors:
      - namespace: karpenter
      - namespace: kube-system
      #- namespace: monitoring
  # All workloads in the "kube-system" Kubernetes namespace will be
  # scheduled onto Fargate:
  #- name: kube-system
  #  selectors:
  #    - namespace: kube-system

#managedNodeGroups:
#  - instanceType: m5.large
#    amiFamily: AmazonLinux2
#    name: mb-ng
#    desiredCapacity: 2
#    minSize: 1
#    maxSize: 10
#    labels: {role: worker}
#    tags:
#     ng-role: worker
