---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mb
  region: eu-west-1
  tags:
    managed_by: 'eksctl'
    karpenter.sh/discovery: mb
    #kubernetes.io/cluster/mb: true
  version: '1.22'

#vpc:
#    clusterEndpoints:
#        publicAccess: true
#        privateAccess: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: karpenter
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Resource: "*"
        Action:
        # Write Operations
        - "ec2:CreateLaunchTemplate"
        - "ec2:CreateFleet"
        - "ec2:RunInstances"
        - "ec2:CreateTags"
        - "iam:PassRole"
        - "ec2:TerminateInstances"
        - "ec2:DeleteLaunchTemplate"
        # Read Operations
        - "ec2:DescribeLaunchTemplates"
        - "ec2:DescribeInstances"
        - "ec2:DescribeSecurityGroups"
        - "ec2:DescribeSubnets"
        - "ec2:DescribeInstanceTypes"
        - "ec2:DescribeInstanceTypeOfferings"
        - "ec2:DescribeAvailabilityZones"
        - "ssm:GetParameter"

fargateProfiles:
  - name: karpenter
    selectors:
      - namespace: karpenter
      - namespace: kube-system
  # All workloads in the "kube-system" Kubernetes namespace will be
  # scheduled onto Fargate:
  #- name: kube-system
  #  selectors:
  #    - namespace: kube-system
