kind: Service
apiVersion: v1
metadata:
  name: helloapp
  namespace: default
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    #service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "karpenter.sh/discovery=mb,Name=helloapp"
spec:
  selector:
    app: helloapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
