apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fake-editor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: fake-user
  namespace: default
