apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: m3-podsec
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - m3-podsec
